#!/bin/bash
pos=(left_front right_front left_back right_back)
for i in ${pos[@]}; do
  rosservice call /urdf_management/urdf_alter_urdf 1 "urdf_management_tutorial/urdfs/quadrotor.urdf" "<joint name=\"${i}_quad_docker_joint\" type=\"fixed\"><parent link=\"quadrotor_dock_${i}_link\" /><child link=\"recharge_dock_link\" /></joint>" "${i}_";
done
exit 0
